### ISSUE TITLE
libswresample/swresample.h not found

### ISSUE THREAD

**Issue by antoniotuzzi** [VCVRack/VCV-Recorder#12]
macosx 10.13

after inching to get lame and all ffmpeg installed

I get this:

```
src/Recorder.cpp:8:10: fatal error: 'libswresample/swresample.h' file not found
#include <libswresample/swresample.h>

```
the `libswresample/swresample.h` seems to be in the correct place

seems like the `-I$(RACK_DIR)/dep/include` from `plugin.mk` doesn't work, or maybe doesn't work because is declared `extern "C"`

**Comment by AndrewBelt** [comment]
Do you have spaces in your path? Rack's build system doesn't support that.

**Comment by antoniotuzzi** [comment]
no, no spaces (I hate because of this... :D )

**Comment by antoniotuzzi** [comment]
doing all process from ZERO after updating all (let you know)

**Comment by antoniotuzzi** [comment]
lame correctly downloaded, compiled (no stops) and installed

**Comment by antoniotuzzi** [comment]
ffmpeg correctly recompiled and installed, but the error is still there

**Comment by AndrewBelt** [comment]
Can you give more context about your problem? The command above the error, the directory listing of `dep/include`, etc

**Comment by antoniotuzzi** [comment]
more info for  you
if I comment out `#include   <libswresample/swresample.h>`
the file is compiled (but with the error of missing symbols)

this means that the others includes are working

context, 
I'm issuing the `make` command

the output is
```
c++  -std=c++11 -stdlib=libc++  -fPIC -I../../include -I../../dep/include -MMD -MP -g -O3 -march=nocona -funsafe-math-optimizations -Wall -Wextra -Wno-unused-parameter -DARCH_MAC -mmacosx-version-min=10.7 -c -o build/src/Recorder.cpp.o src/Recorder.cpp
src/Recorder.cpp:9:12: fatal error: 'libswresample/swresample.h' file not found
#include   "libswresample/swresample.h"
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make: *** [build/src/Recorder.cpp.o] Error 1
```

my  DEP path  is
`dep/include/libswresample/`

the DEP content is

```
drwxr-xr-x   9  staff   288 Apr 17 19:22 ..
drwxr-xr-x   3  staff    96 Apr 17 19:22 lame
drwxr-xr-x   5  staff   160 Apr 17 19:26 libavformat
drwxr-xr-x  20  staff   640 Apr 17 19:26 libavcodec
drwxr-xr-x   4  staff   128 Apr 17 19:26 libswresample
drwxr-xr-x   4  staff   128 Apr 17 19:26 libswscale

drwxr-xr-x  82  staff  2624 Apr 17 19:26 libavutil
```

**Comment by AndrewBelt** [comment]
What is in `dep/include/libswresample`?

**Comment by antoniotuzzi** [comment]
```
-rw-r--r--  1  staff  21785 Apr 17 19:26 swresample.h
-rw-r--r--  1  staff   1718 Apr 17 19:26 version.h
```

**Comment by AndrewBelt** [comment]
Ah, try 9717aa4. I left out the include flag.

**Comment by antoniotuzzi** [comment]
good! Working!
