### ISSUE TITLE
make dep fails on #include <langinfo.h>

### ISSUE THREAD

**Issue by MarcBoule** [VCVRack/VCV-Recorder#14]
Windows 10, Recorder commit https://github.com/VCVRack/VCV-Recorder/commit/1c30f48e7fda871a7c43abdede6e2bdc2e772f63, Rack v1 commit https://github.com/VCVRack/Rack/commit/93bf107d37e3a438d33d36ebdfa635a058c8e70a

```
...
mv -f .deps/lametime.Tpo .deps/lametime.Po
gcc -DHAVE_CONFIG_H  -I. -I.. -I../libmp3lame -I../include -I..    -fPIC -g -O3 -march=nocona     -MT parse.o -MD -MP -MF .deps/parse.Tpo -c -o parse.o parse.c
parse.c:74:10: fatal error: langinfo.h: No such file or directory
 #include <langinfo.h>
          ^~~~~~~~~~~~
compilation terminated.
make[2]: *** [Makefile:500: parse.o] Error 1
make[2] : on quitte le répertoire « /home/mboule/Rack/rdev/Rack/plugins/VCV-Recorder/dep/lame-3.100/frontend »
make[1]: *** [Makefile:452: install-recursive] Error 1
make[1] : on quitte le répertoire « /home/mboule/Rack/rdev/Rack/plugins/VCV-Recorder/dep/lame-3.100 »
make: *** [Makefile:52: dep/lib/libmp3lame.a] Error 2

```

**Comment by Coirt** [comment]
Same with latest of both and Win7

**Comment by jhoar** [comment]
Looks like lame3.1has a problem with mingw

https://sourceforge.net/p/lame/bugs/487/

Fixed in:
https://sourceforge.net/p/lame/svn/6410/
https://sourceforge.net/p/lame/svn/6416/

**Comment by Coirt** [comment]
If you remove that line as Antonio said in  #10 the line replaces itself `lame_init_old` if not found

**Comment by MarcBoule** [comment]
This seems to have been fixed with https://github.com/VCVRack/VCV-Recorder/commit/6dd76d3b3acd7f8da003a217de80b3ad76f5263a. Closing, but will open a new issue with the next error.
