### ISSUE TITLE
dep/ffmpeg folder doesn't exist

### ISSUE THREAD

**Issue by LOGUNIVPM** [VCVRack/VCV-Recorder#21]
I'm building on Linux Mint (Ubuntu based) and I get the following issue with ffmpeg, as if a part of the script did not execute and download the ffmpeg stuff:

`/bin/sh: 1: cd: can't cd to dep/ffmpeg
Makefile:44: recipe for target 'dep/lib/libavcodec.a' failed
`
Indeed there is no ffmpeg in VCV-Recorder/dep/

The make command finishes with lame-3.100 and then starts with ffmpeg but no download is attempted and how could the directory be there. See below:

`make[1]: Leaving directory '/home/leopard/Apps/Rack/Rackv1/plugins/VCV-Recorder/dep/lame-3.100'
mkdir -p dep
cd dep/ffmpeg && ./configure --prefix="/home/leopard/Apps/Rack/Rackv1/plugins/VCV-Recorder/dep" --enable-pic --enable-gpl \
	--disable-programs --disable-doc --disable-avdevice --disable-swresample --disable-postproc --disable-avfilter --disable-network --disable-iconv --disable-alsa --disable-autodetect --disable-everything \
	--enable-protocol=file \
	--enable-muxer=wav --enable-encoder=pcm_s16le --enable-encoder=pcm_s24le --enable-muxer=aiff --enable-encoder=pcm_s16be --enable-encoder=pcm_s24be --enable-libmp3lame --enable-muxer=mp3 --enable-encoder=libmp3lame --enable-muxer=flac --enable-encoder=flac --enable-muxer=ipod --enable-encoder=alac --enable-muxer=mpeg1system --enable-encoder=mpeg2video --enable-encoder=mp2
Makefile:44: recipe for target 'dep/lib/libavcodec.a' failed
`

**Comment by AndrewBelt** [comment]
Probably need to `git submodule update --init` ?

**Comment by LOGUNIVPM** [comment]
Right
