### ISSUE TITLE
Make dep error - cannot find opus

### ISSUE THREAD

**Issue by david-c14** [VCVRack/VCV-Recorder#24]
Building on Ubuntu, libopus appears to have built and installed without error. But building ffmpeg is then failing

`ERROR: opus not found using pkg-config`

**Comment by AndrewBelt** [comment]
Opened ffmpeg bug at https://trac.ffmpeg.org/ticket/8258. Added workaround in deb88db6d22b7d34e63fe592f947b0168471ea3f
