### ISSUE TITLE
won't record between sessions

### ISSUE THREAD

**Issue by michaelpalumbo** [VCVRack/VCV-Recorder#26]
vcv-recorder module where it won't let you record when operating in loaded sessions (i.e. adding a recorder module, when pressing record it works fine, but upon reopening rack (after closing for whatever the reason), the record button no longer responds (stays grey when clicking).

**Comment by AndrewBelt** [comment]
Does setting the output file path in the module context menu allow Recorder to be used again?
Is there information about VCV Recorder printed to `log.txt`?

**Comment by AndrewBelt** [comment]
Cannot reproduce issue and no user response, closing.
