### ISSUE TITLE
recorder module will not work if patch copied to another path

### ISSUE THREAD

**Issue by michaelpalumbo** [VCVRack/VCV-Recorder#27]
possibly related to issue #26 -- and also likely issue 22 in the VCV-Prototype issues thread -- but when a .vcv file containing an instance of the recorder module has been copied to another path, the recorder module will not respond to record button presses.

**Comment by AndrewBelt** [comment]
What do you mean by "copied to another path"?

**Comment by michaelpalumbo** [comment]
If, for instance, I have a .vcv file with a record module in it, and i push it to a git repo. If someone clone's my repo, the path for the record module doesn't reset, it instead seems it gets confused by being on the new system and doesn't respond to mousse clicks.

**Comment by AndrewBelt** [comment]
Okay, I understand now. Fixed in 887a968 by opening the dialog box if the path is set but the directory is not found.

**Comment by michaelpalumbo** [comment]
Great. Thanks Andrew
