### ISSUE TITLE
Recorder uses original filename if patch is renamed (save as)

### ISSUE THREAD

**Issue by veryfungi** [VCVRack/VCV-Recorder#30]
nit picky issue, easily worked around. Windows 7. 

1. open file "patch.vcv" including recorder module and record a file. example "patch-001.wav"
2. rename the file using "save as" to "newpatch.vcv"
3. record a file. The name will be "patch-002.wav" and not "newpatch-001.wav"
4. closing and opening the "newpatch.vcv" file will fix the issue. 

thanks!

**Comment by AndrewBelt** [comment]
The filename in Recorder is not connected in any way to the patch filename.
